vim.cmd([[autocmd! BufWritePost init.lua source init.lua | echom "                         Reloaded init.lua"]])
print("  _______________________________________________________________________ ")
print(" ┊ MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXKOkxdoodx0XWMMMMMMMMMMMMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMMMMMMMMMMMMX0kc;.........'',;lx0NMMMMMMMMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMMMMMMMMMNkc......... .......'',;:xNMMMMMMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMMMMMMMMK'..''''..',;..........',',:dNMMMMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMMMMMMNxclclokKXXXXXN0c.  ........'',:0MMMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMMMMN0c,,,;:clloolc:::;'..............';KMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMMMXxc,;:cclddddllc::c:;'......  ......'lMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMM0;,::cc;;:::clllcclccc;,...   .  .. ..:WMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMW,.'ccoooocclloxxdllccc:,'..          .;MMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMN.,'':dkxo;;cdkkkkkdllc:;'..           ,MMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMN';,;clool,.':loodddlc::;,.. .',,',;:' cMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMM;.:clool:;,:llc::;:::::;,'..'cxxokxod,OMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMWkddolcldlc::cooooolc::;;;,'',lllddxco:XMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMkcdxdddccllooodxkkdoc:;;;;,,,;dcldddl:dMMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMx;;;,:looooddxxOOkxo:;;;;;,,,:c:oddl:cWMMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMx;,:;:cccodxxkkkkxdo:;;::;,,':odl::,;NMMMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMc,:ccloc:;:dkkkxxdollc:::;,,''lo:'. xMMMMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMxlooooooooldxddoooooolc:;,,''';;'. cMMMMMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMW;.';codxxxdollloolllc::;,'',::,...WMMMMMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMMo;:coxkOOOxolllcc:::;,''';:cc:,.'dNMMMMMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMMl,;:ldxxdlc::;,,''....',:lolc;,xKX0KNMMMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMMNl;'..''...........',;:clool:lKXXKKXXNMMMMMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMMMMMNOdl:.........',;::clllc:kXKXKK0KKXKXXNMMMMMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMMMMMMMMMMWO:.....',;::clllloKKK0K00K0XNNNNXXNWWMMMMM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMMMMMMMMMNX0x..'',;:ccclllxkK0K000000KXNNNNNNWWWNNNNM ┊")
print(" ┊ MMMMMMMMMMMMMMMMMMMMWWWNKk00k''.';:ccccclOOK000O0O0000KXXXXNXNNNNWWWN ┊")
print(" ┊ MMMMMMMMMMMMMMMWWWNNNNXO0K000;',',;::::xO0K0O0k0OO00OKKXXKKKXKNKNXXNN ┊")
print(" ┊ MMMMMMMMMMMWNXNNNNXNXKXK0K0Od..',,,,;l0OK00x0xOOk0OxOOKXKKXNKNk0K0NKX ┊")
print(" ┊_______________________________________________________________________┊")
require("daniels")

